/* ESP32 build config for NUT. Not generated by autotools.
 * Keep this file small and explicit so it can track new NUT releases.
 */

#ifndef NUT_ESP32_CONFIG_H
#define NUT_ESP32_CONFIG_H 1

#include "sdkconfig.h"

#define NUT_NETVERSION "1.3"
#define NUT_WEBSITE_BASE "https://networkupstools.org/"

#define PACKAGE "nut"
#define PACKAGE_NAME "nut"
#define PACKAGE_TARNAME "nut"
#define PACKAGE_VERSION "2.8.5"
#define PACKAGE_STRING "nut 2.8.5"
#define PACKAGE_BUGREPORT "https://github.com/networkupstools/nut/issues"
#define PACKAGE_URL "https://networkupstools.org/"
#define VERSION "2.8.5"
#define CC_VERSION "xtensa-esp32s3-elf-gcc"
#define CONFIG_FLAGS "esp32-idf6"

#define CONFPATH "/usr/local/etc/nut"
#define DATADIR "/usr/local/etc/nut"
#define NUT_DATADIR "/usr/local/etc/nut"
#define STATEPATH "/var/db/nut"
#define PIDPATH "/var/db/nut"
#define ALTPIDPATH "/var/db/nut"
#define DRVPATH "/usr/local/libexec/nut"
#define BINDIR "/usr/local/bin"
#define SBINDIR "/usr/local/sbin"
#define LIBDIR "/usr/local/lib"
#define RUN_AS_USER "nut"
#define RUN_AS_GROUP "nut"
#define PORT 3493
#define EXEEXT ""
#define STDC_HEADERS 1
#define TIME_WITH_SYS_TIME 1

#define WITH_ESPUSB 1
#define WITH_USB 1
#define WITH_LIBUSB_0_1 0
#define WITH_LIBUSB_1_0 0
/* Leave WITH_SSL / WITH_OPENSSL / WITH_NSS undefined so netssl.c uses stubs. */
#define WITHOUT_LIBSYSTEMD 1

#define HAVE_STDBOOL_H 1
#define HAVE_STDINT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDARG_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_UNISTD_H 1
#define HAVE_ERRNO_H 1
#define HAVE_LIMITS_H 1
#define HAVE_MATH_H 1
#define HAVE_FLOAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_NETDB_H 1
#define HAVE_POLL_H 1
#define HAVE_SYS_POLL_H 1
#define HAVE_GETOPT_H 1
#define HAVE_DECL_OPTIND 1
#define HAVE_ATEXIT 1
#define HAVE_GMTIME_R 1
#define HAVE_LOCALTIME_R 1
#define HAVE_STRTOF 1
#define HAVE_USLEEP 1
#define HAVE_SETEUID 1
#define HAVE_STRPTIME 1
#define HAVE_SNPRINTF 1
#define HAVE_VSNPRINTF 1
#define HAVE_VA_COPY 1
#define HAVE_VA_COPY_VARIANT 1
#define HAVE_STRNLEN 1
#define HAVE_STRCASECMP 1
#define HAVE_STRNCASECMP 1
#define HAVE_SETENV 1
#define HAVE_UNSETENV 1
#define HAVE_USECONDS_T 1
#define HAVE_SUSECONDS_T 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_FILENO 1
#define HAVE_LIBREGEX 1
#define WANT_TIMEGM_FALLBACK 1
#define FLEXIBLE_ARRAY_MEMBER

#ifndef EAI_SYSTEM
#define EAI_SYSTEM 11
#endif

#ifdef __cplusplus
extern "C" {
#endif

void rtos_yield(void);
const char *gai_strerror(int errcode);

#ifdef __cplusplus
}
#endif

#endif /* NUT_ESP32_CONFIG_H */
